

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: antho
  password: ixY3z5uvifbFSZS73gWicvp1c6w7PYiy

development:
  <<: *default
  database: SeatMe_development
  host: localhost
  port: 5432 # The default port for PostgreSQL


test:
  <<: *default
  database: SeatMe_test

production:
  <<: *default
  database: SeatMe_production
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  region: <%= ENV['DATABASE_REGION'] %>
  url: <% ENV['DATABASE_URL'] %>

  # port: <%= ENV['DATABASE_PORT'] %>
  # host: 127.0.0.1
