

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 3000
  username: antho
  password: ixY3z5uvifbFSZS73gWicvp1c6w7PYiy

development:
  <<: *default
  database: SeatMe_development

test:
  <<: *default
  database: SeatMe_test

  production:
  <<: *default
  database: SeatMe_production
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  region: <%= ENV['DATABASE_REGION'] %>
